name: weekly-scrape
on:
  schedule:
    - cron: "0 8 * * FRI"  # chaque vendredi 08:00 UTC
  workflow_dispatch: {}

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MIN_EXPONENTS: 80
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install requests beautifulsoup4
      - name: Run scraper
        run: python bot/main.py
