name: weekly-scrape

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    env:
      SOURCE_URL: ${{ secrets.SOURCE_URL }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      PYTHONUNBUFFERED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper (creates logs and artifacts)
        run: |
          mkdir -p /tmp/scrape-debug
          LOG_TXT=/tmp/scrape-debug/scrape-debug.txt
          LOG_JSON=/tmp/scrape-debug/full-run.json
          echo "=== START $(date -u) ===" >"$LOG_TXT"
          echo "ENV: SOURCE_URL='${SOURCE_URL}'" >>"$LOG_TXT"
          echo "ENV: DISCORD_WEBHOOK_SET='${DISCORD_WEBHOOK:+yes}'" >>"$LOG_TXT"
          echo "" >>"$LOG_TXT"
          echo "=== CURL HEAD ===" >>"$LOG_TXT"
          curl -I --fail --location --max-time 15 "${SOURCE_URL}" >>"$LOG_TXT" 2>&1 || echo "curl HEAD failed" >>"$LOG_TXT"
          echo "" >>"$LOG_TXT"
          echo "=== CURL FIRST LINES (HTML) ===" >>"$LOG_TXT"
          curl --fail --location --max-time 15 "${SOURCE_URL}" -s | sed -n '1,200p' >>"$LOG_TXT" 2>&1 || echo "curl show failed" >>"$LOG_TXT"
          echo "" >>"$LOG_TXT"
          echo "=== RUN python bot/main.py ===" >>"$LOG_TXT"
          python -u bot/main.py >>"$LOG_TXT" 2>&1 || echo "python script exited with non-zero" >>"$LOG_TXT"
          echo "" >>"$LOG_TXT"
          echo "=== COPY JSON LOG IF EXISTS ===" >>"$LOG_TXT"
          if [ -f /tmp/scrape-debug/full-run.json ]; then cp /tmp/scrape-debug/full-run.json "$LOG_JSON"; echo "copied json log" >>"$LOG_TXT"; fi
          echo "=== END $(date -u) ===" >>"$LOG_TXT"
          echo "WROTE LOGS TO $LOG_TXT and $LOG_JSON"
        shell: bash

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scrape-debug
          path: /tmp/scrape-debug
