name: weekly-videgrenier

on:
  schedule:
    - cron: '0 7 * * FRI'   # chaque vendredi à 07h00 UTC
  workflow_dispatch:         # permet de le lancer manuellement depuis GitHub

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python fetch_videgreniers.py
